name: Heroku Awake

on:
  schedule:
    - cron: "0,30 8-23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://miniflux92.herokuapp.com"
